baseURL = 'https://hugo-leung.github.io/'
locale = 'en-us'
title = 'Ching Him Leung'
theme = "personal-web"
copyright="Ching Him Leung"



[pagination]
	disableAliases = false
	pagerSize = 10
	path = 'page'

[params.intro]
	main = "Hi, I am Ching&nbsp;Him Leung"
	sub = "Hall C Postdoc at Jefferson Lab"

[taxonomies]
  tag = "tags"

[params]
  breadcrumb = true
  accentColor = "#FD3519"
	mainSections = []
#	rendererSafe = true
  math = true

[params.sidebar]
	backgroundImage = "/images/sidebar.jpg"
	logo = "/images/profile.jpg"

[params.social]
	github = "https://github.com/Hugo-Leung"
	orcid = "https://orcid.org/0000-0001-7907-3728"
	googlescholar = "https://scholar.google.com/citations?user=Th7ghh8AAAAJ&hl=en"
	inspirehep = "https://inspirehep.net/authors/1926084"
	email = "mailto:cleung@jlab.org"
[params.assets]
	favicon = "/favicon.ico"

[params.notFound]
	image = "/images/404.svg"
	h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.KaTeX]
	version = "0.18.4"
	css_integrity = "sha384-u1zONI5gPXUx0UKI62c75/zww972y0v2rSK5ZYlVdS6xEuWDeZWUI66v6t1gvlXJ"
	js_integrity = "sha384-ykMNcWQhhTUb0YV9SPpPUFURHZ+tWmubkakGBP+OgNK/UXdO2gtzglWx0Rj9hnO3"
	auto_render_integrity = "sha384-bjyGPfbij8/NDKJhSGZNP/khQVgtHUE5exjm4Ydllo42FwIgYsdLO2lXGmRBf5Mz"

[menu]

[[menu.main]]
	identifier = "Research"
	name = "Research"
	title = "Research"
	url = "/research/"
	weight = -120

[[menu.main]]
	identifier = "Talks"
	name = "Talks"
	title = "Talks"
	url = "/talks/"
	weight = -110

[[menu.main]]
	identifier = "Publications"
	name = "Publications"
	title = "Publications"
	url = "/publications/"
	weight = -100

[[menu.main]]
	identifier = "CV"
	name = "CV"
	title = "CV"
	url = "/cv/"
	weight = -90

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[sitemap]
  changeFreq = ''
  disable = false
  filename = 'sitemap.xml'
  priority = -1


